config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "user_tasks/add_new", to: "user_tasks#add_task", as: "user_task_add"
  post "/add_tasks_to_user", to: "user_tasks#add_tasks_to_user", as: "add_tasks_to_user"

  # Defines the root path route ("/")
  # root "posts#index"

  # resources :registration do
  #   collection do
  #     get :interests
  #   end
  # end

  resources :achievements do
    resources :user_achievements
  end

  resources :users do
    resources :user_interests, except: %i[show]
    resources :user_tasks do
      post :add_task_to_user
    end
  end

  resources :tasks do
    resources :interest_tasks, only: %i[new create]
    # resources :user_tasks, except: %i[]
  end

  # resources :interests, only: %i[index]
  # resources :user_interests
  # resources :interest_task
  # end

  resources :user_tasks do
    member do
      patch 'toggle_complete'
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  include PgSearch::Model

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true

  has_many :interest_tasks
  has_many :interests, through: :interest_tasks, dependent: :destroy
  has_many :user_tasks
  has_many :users, through: :user_tasks

  # app/models/task.rb
class Task < ApplicationRecord
  # Assuming you have a column called image_title in your tasks table
  def unsplash_image_url

    response = HTTParty.get("https://api.unsplash.com/search/photos?query=#{CGI.escape(image_title)}&client_id=YOUR_UNSPLASH_API_KEY")
    if response.code == 200 && !response.parsed_response["results"].empty?
      response.parsed_response["results"][0]["urls"]["regular"]
    else
      # If no image found, return a default image URL or handle it as per your requirement
      'https://example.com/default-image.jpg'
    end
  end
end


  pg_search_scope :global_search,
    against: [:title, :description],
    associated_against: {
      interests: [:title]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
    @interests = Interest.all

    @tasks = if params[:query].present?
                Task.includes(:interests).joins(:interests).
                where("tasks.title ILIKE ? OR tasks.description ILIKE ? OR interests.title ILIKE ? ", "%#{params[:query]}%", "%#{params[:query]}%","%#{params[:query]}%")
                .order(Arel.sql('RANDOM()')).page(params[:page]).per(21)
              else
                Task.includes(:interests).all.order(:title).page(params[:page]).per(21)
             end


    respond_to do |format|
      format.html
      format.text { render partial: 'tasks/lists', locals: { tasks: @tasks }, formats: [:html]}
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path, notice: "Task created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "Task updated"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other, notice: "Task deleted"
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/views/tasks/_interest.html.erb
<div class="container1 interests-container mt-4">
  <div class="row">
    <% @interests.each_slice(4) do |slice| %>
      <% slice.each do |interest| %>
        <div class="col-md-3 mb-3">
           <%= button_to tasks_path(query: interest.title), method: :get, class: "btn btn-secondary btn-block interest-button", remote: true, data: { title: interest.title } do %>
            <%= image_tag "#{interest.title.downcase.gsub(/\s+/, '_')}.png", alt: interest.title, class: "interest-image"  %>
            <%= interest.title %>
            <% end%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/_lists.html.erb
<div data-search-tasks-target="list", data-interest-search-target="list", class='row lists-render'>
  <% tasks.each do |task| %>
    <% unless task.user_tasks.exists? %>
      <div class="col-md-4 mb-4 align-right">
        <%= link_to task_path(task), class: " card-link text-decoration-none" do %>
          <div class="card shadow h-100" style="border-radius: 0.5rem;">
            <div class="card-body">
                <h3 class="card-title"><%= task.title %></h3>
                 <div class="add_tasks">
                    <%= link_to 'Add task', user_task_add_path(user_id: current_user, task_id: task), data: { turbo_method: :post }, class: 'btn btn-primary mt-2' %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="pagination d-flex justify-content-end">
    <%= paginate tasks %>
  </div>

</div>

<%= puts @user_tasks %>

app/views/tasks/index.html.erb
<div class="relative-container">
  <div data-controller="search-tasks interest-search typing-effect">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: tasks_path, method: :get, html: { class: "custom-form" }, data: { search_tasks_target: "form" } do |f| %>
        <div class="input-group">
          <%= image_tag("search.png", class: "search-image", alt: "Search Image") %>
          <%= f.text_field :query,
                class: "form-control custom-input",
                placeholder: "Search for more tasks...",
                value: params[:query],
                data: {
                  typing_effect_target: "placeholder",
                  search_tasks_target: "query",
                  action: "keyup->search-tasks#search"
                }
            %>
            <div class="input-group-append d-none">
              <%= f.submit "Search" %>
            </div>
        </div>
      <% end %>
    </div>
  </div>



    <div class="task-grid-container">
      <div class="container">
        <%= render "interest", tasks: @tasks %>
      </div>
      <div class="container2">
        <h2>Choose your favourite task! <i class="far fa-check-square"></i></h2>
        <div class="list-render">
          <%= render "lists", tasks: @tasks %>
        </div>
      </div>
    </div>
  </div>
</div>
<footer>
  <%= render "shared/foot" %>
</footer>

app/views/tasks/show.html.erb
 <div class ="height">
  <div class="container_task pt-3">
    <div class="task_t">
      <h2><%= @task.title %></h2>
    </div>
    <div class="task_description">
      <p><%= @task.description %></p>
    </div>
    <div class="task_add mt-3">
      <%= link_to 'Add to my tasks', user_task_add_path(user_id: current_user, task_id: @task.id), data: { turbo_method: :post }, class: 'btn btn-primary' %>
    </div>
  </div>
</div>