config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "user_tasks/add_new", to: "user_tasks#add_task", as: "user_task_add"
  post "/add_tasks_to_user", to: "user_tasks#add_tasks_to_user", as: "add_tasks_to_user"

  # Defines the root path route ("/")
  # root "posts#index"

  # resources :registration do
  #   collection do
  #     get :interests
  #   end
  # end

  resources :achievements do
    resources :user_achievements
  end

  resources :users do
    resources :user_interests, except: %i[show]
    resources :user_tasks do
      post :add_task_to_user
    end
  end

  resources :tasks do
    resources :interest_tasks, only: %i[new create]
    # resources :user_tasks, except: %i[]
  end

  # resources :interests, only: %i[index]
  # resources :user_interests
  # resources :interest_task
  # end

  resources :user_tasks do
    member do
      patch 'toggle_complete'
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_foot.html.erb
  <div class="container">
    <div class="footer-columns">
      <div class="footer-column">
        <h3>About Us</h3>
        <a href="link">Join our team!</a>
        <a href="link">Contact us</a>
        <a href="link">invite friends</a>
      </div>
      <div class="footer-column">
        <h3>Contact Us</h3>
        <h4>Email: Sisyphus@contact.com<br>Phone: +447842065915</h4>
      </div>
      <div class="footer-column">
        <h3>Follow Us</h3>
        <ul class="social-icons">
          <li><a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a></li>
          <li><a href="#" class="social-icon"><i class="fab fa-twitter"></i></a></li>
          <li><a href="#" class="social-icon"><i class="fab fa-instagram"></i></a></li>
          <h4>We would love to share more with you!</h4>
        </ul>
      </div>
      <div class="footer-column">
        <h3>Get Our App</h3>
        <ul class="app-icons">
          <li><a href="#" class="app-icon"><i class="fab fa-apple"></i></a></li>
          <li><a href="#" class="app-icon"><i class="fab fa-google-play"></i></a></li>
        </ul>
      </div>
      <div class="footer-column d-none"></div>
    </div>
  </div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="footer-columns">
      <div class="footer-column">
        <h3>About Us</h3>
        <a href="link">Join our team!</a>
        <a href="link">Contact us</a>
        <a href="link">invite friends</a>
      </div>
      <div class="footer-column">
        <h3>Contact Us</h3>
        <h4>Email: Sisyphus@contact.com<br>Phone: +447842065915</h4>
      </div>
      <div class="footer-column">
        <h3>Follow Us</h3>
        <ul class="social-icons">
          <li><a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a></li>
          <li><a href="#" class="social-icon"><i class="fab fa-twitter"></i></a></li>
          <li><a href="#" class="social-icon"><i class="fab fa-instagram"></i></a></li>
          <h4>We would love to share more with you!</h4>
        </ul>
      </div>
      <div class="footer-column">
        <h3>Get Our App</h3>
        <ul class="app-icons">
          <li><a href="#" class="app-icon"><i class="fab fa-apple"></i></a></li>
          <li><a href="#" class="app-icon"><i class="fab fa-google-play"></i></a></li>
        </ul>
        <div class="footer-column-divider get-our-app-divider"></div>
    </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "sisyphus-logo.png", width: "150px", height: "50px" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Challenges", tasks_path, class: "nav-link" %>
          </li>
          <li class="navbar-nav me-auto">
            <%= link_to "Achievements", achievements_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://i.ibb.co/yVGxFPR/2.png", class: "user", alt: "dropdown menu", width: "50", height: "50" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Interests", new_user_user_interest_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="fas fa-bell"></i> <!-- Bell icon -->
          </a>
        </li>
      </ul>
      </ul>
    </div>
  </div>
</div>