config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "user_tasks/add_new", to: "user_tasks#add_task", as: "user_task_add"
  post "/add_tasks_to_user", to: "user_tasks#add_tasks_to_user", as: "add_tasks_to_user"

  # Defines the root path route ("/")
  # root "posts#index"

  # resources :registration do
  #   collection do
  #     get :interests
  #   end
  # end

  resources :achievements do
    resources :user_achievements
  end

  resources :users do
    resources :user_interests, except: %i[show]
    resources :user_tasks do
      post :add_task_to_user
    end
  end

  resources :tasks do
    resources :interest_tasks, only: %i[new create]
    # resources :user_tasks, except: %i[]
  end

  # resources :interests, only: %i[index]
  # resources :user_interests
  # resources :interest_task
  # end

  resources :user_tasks do
    member do
      patch 'toggle_complete'
    end
  end
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/controllers/user_interests_controller.rb
class UserInterestsController < ApplicationController
  before_action :set_user, only: [:destroy]
  before_action :set_user_interest, only: [:destroy]
  # def index
  #   @user_interests = current_user.user_interests.includes(:interest)
  # end

  def new
    @user_interest = UserInterest.new
    @interests = Interest.all
  end

  def create
    @user_interest = UserInterest.new(user_interest_params)
    if @user_interest.save
      redirect_to new_user_user_interest_path
    else
      @interests = Interest.all
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @user_interest = UserInterest.find(params[:id])
    @user_interest.destroy
    redirect_to new_user_user_interest_path, notice: "User interest successfully deleted."
  end

  private

  def user_interest_params
    params.require(:user_interest).permit(:user_id, :interest_id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_user_interest
    @user_interest = @user.user_interests.find(params[:id])
  end

end

app/views/user_interests/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <div class="login-box d-flex justify-content-center align-items-center">
        <!-- Interests Section -->
        <div class="interests-section">
          <h2 class=" title1 text-center mb-4">Select your interests</h2>
          <!-- Displaying interests -->
          <% @interests.each_slice(2) do |interest_group| %>
            <div class="row mb-3">
              <% interest_group.each do |interest| %>
                <div class="col-md-6">
                  <% if current_user.interests.include?(interest) %>
                    <%= button_to user_user_interest_path(current_user, interest.user_interests.find_by(interest_id: interest.id)), method: :delete, class: "btn btn-secondary btn-block interest-button user-interest", remote: true do %>
                      <%= image_tag "#{interest.title.downcase.gsub(/\s+/, '_')}.png", alt: interest.title, class: "interest-image"  %>
                      <%= interest.title %>
                      <span class="selected-indicator">Selected</span>
                    <% end %>
                  <% else %>
                    <%= button_to user_user_interests_path(current_user), method: :post, class: "btn btn-secondary btn-block interest-button", remote: true, params: { user_interest: {user_id: current_user.id, interest_id: interest.id } } do %>
                      <%= image_tag "#{interest.title.downcase.gsub(/\s+/, '_')}.png", alt: interest.title, class: "interest-image"  %>
                      <%= interest.title %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>