config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "user_tasks/add_new", to: "user_tasks#add_task", as: "user_task_add"
  post "/add_tasks_to_user", to: "user_tasks#add_tasks_to_user", as: "add_tasks_to_user"

  # Defines the root path route ("/")
  # root "posts#index"

  # resources :registration do
  #   collection do
  #     get :interests
  #   end
  # end

  resources :achievements do
    resources :user_achievements
  end

  resources :users do
    resources :user_interests, except: %i[show]
    resources :user_tasks do
      post :add_task_to_user
    end
  end

  resources :tasks do
    resources :interest_tasks, only: %i[new create]
    # resources :user_tasks, except: %i[]
  end

  # resources :interests, only: %i[index]
  # resources :user_interests
  # resources :interest_task
  # end

  resources :user_tasks do
    member do
      patch 'toggle_complete'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sisyphus - The legend of you trying to get stuff done</title>
    <%= favicon_link_tag(source = "favicon.ico", options = {}) %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Sisyphus">
    <meta property="og:description" content="The legend of you trying to get stuff done">
    <meta property="og:type" content="web-application">
    <meta property="og:url" content="https://www.deedsofsisyphus.com/">
    <meta property="og:image" content="https://opengraph.b-cdn.net/production/documents/87947823-9aed-42c3-8bb6-13fa0a7881bd.png?token=uxcatX2OKQbK4-7gyQoKNk9wNDHGELh6JcY5uwKdIEU&height=630&width=1200&expires=33248364326">
    <%= javascript_include_tag 'js/pie_chart' %> <!-- Include your new JavaScript file -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# <%= javascript_include_tag 'js/pie_chart' %> <!-- Include your new JavaScript file -->
  </head>

  <body>
    <%# <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> %>
    <%# <%= javascript_include_tag 'confetti' %>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <div class="boulder-container-container" data-controller="roll-boulder">
      <div class="background-container">
        <div class="boulder-container" data-roll-boulder-target="hill">
          <div class="text-bubble-container" data-controller="speak-boulder" data-user-logged-in="<%= user_signed_in? %>" data-username="<%= current_user.username if user_signed_in? %>" data-speak-boulder-target="boulder">
            <button class="image-button" data-roll-boulder-target="boulder"><%= image_tag "boulder.png", alt: "boulder", class: "boulder-image" %></button>
            <div class="text-bubble hidden" data-speak-boulder-target="textBubble" data-roll-boulder-target="textBubble"></div>
          </div>
        </div>
        <div class="diagonal-line"></div>
        <div style="position: relative; z-index: 100;">
          <%= yield %>
          <% if user_signed_in? %>
            <div class="hidden-form">
              <div class="card-list user_tasks" data-controller="fade-in" data-target="fade-in.secondFadeInElement">
                <h3 class="fs-2 fw-bold"> Your tasks for the day </h3>
                <% interests = Interest.includes(tasks: :user_tasks).order(:title) %>
                <% interests.each do |interest| %>
                  <% interest_tasks = interest.tasks.select { |task| task.user_tasks.exists?(user_id: current_user ) } %>
                  <% next if interest_tasks.empty? %>
                  <div class="interest-group">
                    <h4><%= interest.title %></h4>
                    <% interest_tasks.each do |task| %>
                    <% user_task = task.user_tasks.find_by(user_id: current_user.id) %>
                    <div class="d-flex">
                      <% if user_task %>
                      <div class="task-card d-flex align-items-center justify-content-between" data-roll-boulder-target="card">
                        <h4 class="user_task col-sm-8"><%= link_to task.title, user_user_task_path(current_user, user_task), class: "text-decoration-none text-dark" %></h4>
                        <div class="button-container" data-controller="complete-button">
                          <%= form_with(model: user_task, class: "check_form text-lg inline-block w-72 d-flex", url: user_user_task_path(current_user, user_task), method: :patch, data: { complete_button_target: "form", roll_boulder_target: "form" } ) do |f| %>
                            <div class="checkbox-wrapper-44 m-2">
                              <label class="toggleButton">
                                <%= f.check_box :complete, data: { user_id: user_task.user_id, id: user_task.id, complete_button_target: "button", action: "roll-boulder#tick complete-button#tick" }, class: "check_box d-none" %>
                                <div>
                                  <svg viewBox="0 0 44 44">
                                    <path d="M14,24 L21,31 L39.7428882,11.5937758 C35.2809627,6.53125861 30.0333333,4 24,4 C12.95,4 4,12.95 4,24 C4,35.05 12.95,44 24,44 C35.05,44 44,35.05 44,24 C44,19.3 42.5809627,15.1645919 39.7428882,11.5937758" transform="translate(-2.000000, -2.000000)"></path>
                                  </svg>
                                </div>
                              </label>
                            </div>
                            <div class="r-button p-1">
                              <button data-action="click->roll-boulder#remove" class="fa-solid fa-trash text-center"></button>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="card-list user_tasks" data-controller="fade-in" data-target="fade-in.secondFadeInElement">
              <h3 class="fs-2 fw-bold">Please login or sign up to see this content</h3>
              <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary custom-login-button" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>